defaults:
  - /benchmark/nav/objectnav: objectnav_hm3d
  - /habitat/task/lab_sensors:
      - base_explorer
      - compass_sensor
      - gps_sensor
      - heading_sensor
  - /habitat/task/measurements:
    - exploration_map
  - _self_

habitat:
  environment:
    iterator_options:
      max_scene_repeat_steps: 50000
  task:
    success_reward: 2.5
    slack_reward: -1e-3
    lab_sensors:
      base_explorer:
        turn_angle: 30
    measurements:
      success:
        success_distance: 1.0
  dataset:
    split: val
    data_path: data/datasets/objectnav/hm3d/v1/{split}/{split}.json.gz
